theme: jekyll-theme-minimal
title: The OECD Weekly Tracker of economic activity
description:  
logo: https://legalinstruments.oecd.org/dist/img/oecd-logo-big.png
show_downloads: "false"
minimal_mistakes_skin: "contrast" # "air", "aqua", "default", "dark", "dirt", "neon", "mint", "plum" "sunrise"
kramdown:
  math_engine: mathjax
#google_analytics: [Your Google Analytics tracking ID]

