theme: jekyll-theme-minimal
title: The OECD Weekly Tracker of economic activity
logo: https://legalinstruments.oecd.org/dist/img/oecd-logo-big.png
show_downloads: "false"
#google_analytics: [Your Google Analytics tracking ID]

